version: 2.1

jobs:
  test-linux:
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    machine:
      image: ubuntu2204:current
    steps:
      - checkout
      - run:
          name: "Test"
          command: "swift test"

workflows:
  test:
    jobs:
      - test-linux
