version: 2.1

jobs:
  test-mac:
    # See: https://circleci.com/docs/configuration-reference/#macos-execution-environment
    # See: https://circleci.com/docs/using-macos/#supported-xcode-versions
    macos:
      xcode: 15.0.0
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - run:
          name: "Mac Test"
          command: swift test

  test-linux:
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: sudo apt-get update
      # See: https://www.swift.org/install/linux/#installation-via-tarball
      - run: DEBIAN_FRONTEND=noninteractive sudo apt-get install -y binutils git gnupg2 libc6-dev libcurl4-openssl-dev libedit2 libgcc-9-dev libpython3.8 libsqlite3-0 libstdc++-9-dev libxml2-dev libz3-dev pkg-config tzdata unzip zlib1g-dev
      - run:
          wget https://download.swift.org/swift-5.9-release/ubuntu2204/swift-5.9-RELEASE/swift-5.9-RELEASE-ubuntu22.04.tar.gz &&
          wget https://download.swift.org/swift-5.9-release/ubuntu2204/swift-5.9-RELEASE/swift-5.9-RELEASE-ubuntu22.04.tar.gz.sig &&
          gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys '7463 A81A 4B2E EA1B 551F  FBCF D441 C977 412B 37AD' '1BE1 E29A 084C B305 F397  D62A 9F59 7F4D 21A5 6D5F' 'A3BA FD35 56A5 9079 C068  94BD 63BC 1CFE 91D3 06C6' '5E4D F843 FB06 5D7F 7E24  FBA2 EF54 30F0 71E1 B235' '8513 444E 2DA3 6B7C 1659  AF4D 7638 F1FB 2B2B 08C4' 'A62A E125 BBBF BB96 A6E0  42EC 925C C1CC ED3D 1561' '8A74 9566 2C3C D4AE 18D9  5637 FAF6 989E 1BC1 6FEA' 'E813 C892 820A 6FA1 3755  B268 F167 DF1A CF9C E069' &&
          gpg --keyserver hkp://keyserver.ubuntu.com --refresh-keys Swift &&
          gpg --verify ./swift-5.9-RELEASE-ubuntu22.04.tar.gz.sig &&
          tar xzf ./swift-5.9-RELEASE-ubuntu22.04.tar.gz
      - run:
          name: "Linux Test"
          command: export PATH="$("readlink" "-e" "./swift-5.9-RELEASE-ubuntu22.04")"/usr/bin/:"${PATH}" && swift test

workflows:
  test:
    jobs:
      - test-mac
      - test-linux
